# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('op', models.FloatField()),
                ('cl', models.FloatField()),
                ('vloume', models.IntegerField()),
            ],
        ),
    ]
